name: go_deployer

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Run tests
      run: go test go_test.go

    - name: Build
      run: go build ./main.go

    - name: Deploy
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        ssh vagrant@192.168.105.3 'if systemctl --all --state=running | grep -q main; then sudo systemctl stop main; fi'
        scp ./main vagrant@192.168.105.3:/home/vagrant
        ssh vagrant@192.168.105.3 'sudo systemctl start main'

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: main
        path: ./main
