name: go_deployer

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Run tests
      run: go test go_test.go

    - name: Build
      run: go build ./main.go

    - name: Deploy
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} 'if systemctl --all --state=running | grep -q main; then sudo systemctl stop main; fi'
        scp ./main ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.USERNAME }}
        ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} 'sudo systemctl start main'

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: main
        path: ./main
