name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Run tests
      run: ls && go test

    - name: Build
      run: go build -o main

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: main
        path: ./main
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
